export const USER1 = 'Pradeep Biswas'
export const USER2 = 'Chandan Biswas'
export const USER3 = 'Ritik Pawar'
export const USER4 = 'Kalpesh Mahajan'
export const USER5 = 'Harsh Zodape'
export const USER6 = 'Ishan Chaudhary'
export const USER7 = 'Rahul Gupta'
export const USER8 = 'Parth Bhawsar'